package com.xiaoxu.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeam<M extends BaseTeam<M>> extends JbootModel<M> implements IBean {

	/**
	 * id
	 */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * id
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 队伍名称
	 */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 队伍名称
     */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 描述
	 */
	public void setDescription(java.lang.String description) {
		set("description", description);
	}

    /**
     * 描述
     */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 最大人数
	 */
	public void setMaxNum(java.lang.Integer maxNum) {
		set("maxNum", maxNum);
	}

    /**
     * 最大人数
     */
	public java.lang.Integer getMaxNum() {
		return getInt("maxNum");
	}

	/**
	 * 过期时间
	 */
	public void setExpireTime(java.util.Date expireTime) {
		set("expireTime", expireTime);
	}

    /**
     * 过期时间
     */
	public java.util.Date getExpireTime() {
		return getDate("expireTime");
	}

	/**
	 * 用户id（队长 id）
	 */
	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}

    /**
     * 用户id（队长 id）
     */
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	/**
	 * 0 - 公开，1 - 私有，2 - 加密
	 */
	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

    /**
     * 0 - 公开，1 - 私有，2 - 加密
     */
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	/**
	 * 密码
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}

    /**
     * 密码
     */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}



}

