package com.xiaoxu.modelbase;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	/**
	 * 用户昵称
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}

    /**
     * 用户昵称
     */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 账号
	 */
	public void setUserAccount(java.lang.String userAccount) {
		set("userAccount", userAccount);
	}

    /**
     * 账号
     */
	public java.lang.String getUserAccount() {
		return getStr("userAccount");
	}

	/**
	 * 用户头像
	 */
	public void setAvatarUrl(java.lang.String avatarUrl) {
		set("avatarUrl", avatarUrl);
	}

    /**
     * 用户头像
     */
	public java.lang.String getAvatarUrl() {
		return getStr("avatarUrl");
	}

	/**
	 * 个人描述
	 */
	public void setProfile(java.lang.String profile) {
		set("profile", profile);
	}

    /**
     * 个人描述
     */
	public java.lang.String getProfile() {
		return getStr("profile");
	}

	/**
	 * 性别
	 */
	public void setGender(java.lang.Integer gender) {
		set("gender", gender);
	}

    /**
     * 性别
     */
	public java.lang.Integer getGender() {
		return getInt("gender");
	}

	/**
	 * 密码
	 */
	public void setUserPassword(java.lang.String userPassword) {
		set("userPassword", userPassword);
	}

    /**
     * 密码
     */
	public java.lang.String getUserPassword() {
		return getStr("userPassword");
	}

	/**
	 * 邮箱
	 */
	public void setEmail(java.lang.String email) {
		set("email", email);
	}

    /**
     * 邮箱
     */
	public java.lang.String getEmail() {
		return getStr("email");
	}

	/**
	 * 状态 0-正常
	 */
	public void setUserStatus(java.lang.Integer userStatus) {
		set("userStatus", userStatus);
	}

    /**
     * 状态 0-正常
     */
	public java.lang.Integer getUserStatus() {
		return getInt("userStatus");
	}

	/**
	 * 电话
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

    /**
     * 电话
     */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * 创建时间
	 */
	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreateTime() {
		return getDate("createTime");
	}

	/**
	 * 更新时间
	 */
	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

    /**
     * 更新时间
     */
	public java.util.Date getUpdateTime() {
		return getDate("updateTime");
	}



	/**
	 * 0-普通用户  1-管理员
	 */
	public void setUserRole(java.lang.Integer userRole) {
		set("userRole", userRole);
	}

    /**
     * 0-普通用户  1-管理员
     */
	public java.lang.Integer getUserRole() {
		return getInt("userRole");
	}

	/**
	 * 标签列表
	 */
	public void setTags(java.lang.String tags) {
		set("tags", tags);
	}

    /**
     * 标签列表
     */
	public java.lang.String getTags() {
		return getStr("tags");
	}

}

