package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseBlog;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "blog", primaryKey = "id")
public class Blog extends BaseBlog<Blog> {

}

