package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseChat;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "chat", primaryKey = "id")
public class Chat extends BaseChat<Chat> {

}

