package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseComment;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "comment", primaryKey = "id")
public class Comment extends BaseComment<Comment> {

}

