package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseFollow;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "follow", primaryKey = "id")
public class Follow extends BaseFollow<Follow> {

}

