package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseFriend;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "friend", primaryKey = "id")
public class Friend extends BaseFriend<Friend> {

}

