package com.xiaoxu.model.entity;

import com.xiaoxu.model.modelbase.BaseMessage;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "message", primaryKey = "id")
public class Message extends BaseMessage<Message> {

}

