package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseTag;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "tag", primaryKey = "id")
public class Tag extends BaseTag<Tag> {

}

