package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseTeam;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "team", primaryKey = "id")
public class Team extends BaseTeam<Team> {

}

