package com.xiaoxu.model.entity;

import io.jboot.db.annotation.Table;
import com.xiaoxu.modelbase.BaseTeam;

/**
 * Generated by Jboot.
 */
@Table(tableName = "team", primaryKey = "id")
public class Team extends BaseTeam<Team> {
	
}

