package com.xiaoxu.model.entity;


import com.xiaoxu.model.modelbase.BaseUserTeam;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_team", primaryKey = "id")
public class UserTeam extends BaseUserTeam<UserTeam> {

}

