package com.xiaoxu.model.entity;

import io.jboot.db.annotation.Table;
import com.xiaoxu.modelbase.BaseUser;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user", primaryKey = "id")
public class User extends BaseUser<User> {
	
}

