package com.xiaoxu.model.entity;

import io.jboot.db.annotation.Table;
import com.xiaoxu.modelbase.BaseUserTeam;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user_team", primaryKey = "id")
public class UserTeam extends BaseUserTeam<UserTeam> {
	
}

