package com.xiaoxu.model.entity;

import com.xiaoxu.model.modelbase.BaseUser;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "user", primaryKey = "id")
public class User extends BaseUser<User> {

}

