package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeam<M extends BaseTeam<M>> extends JbootModel<M> implements IBean {

    /**
     * id
     */
    public void setId(Long id) {
        set("id", id);
    }

    /**
     * id
     */
    public Long getId() {
        return getLong("id");
    }

    /**
     * 队伍名称
     */
    public void setName(String name) {
        set("name", name);
    }

    /**
     * 队伍名称
     */
    public String getName() {
        return getStr("name");
    }

    /**
     * 描述
     */
    public void setDescription(String description) {
        set("description", description);
    }

    /**
     * 描述
     */
    public String getDescription() {
        return getStr("description");
    }

    /**
     * 最大人数
     */
    public void setMaxNum(Integer maxNum) {
        set("maxNum", maxNum);
    }

    /**
     * 最大人数
     */
    public Integer getMaxNum() {
        return getInt("maxNum");
    }

    /**
     * 过期时间
     */
    public void setExpireTime(java.util.Date expireTime) {
        set("expireTime", expireTime);
    }

    /**
     * 过期时间
     */
    public java.util.Date getExpireTime() {
        return getDate("expireTime");
    }

    /**
     * 用户id（队长 id）
     */
    public void setUserId(Long userId) {
        set("userId", userId);
    }

    /**
     * 用户id（队长 id）
     */
    public Long getUserId() {
        return getLong("userId");
    }

    /**
     * 0 - 公开，1 - 私有，2 - 加密
     */
    public void setStatus(Integer status) {
        set("status", status);
    }

    /**
     * 0 - 公开，1 - 私有，2 - 加密
     */
    public Integer getStatus() {
        return getInt("status");
    }

    /**
     * 密码
     */
    public void setPassword(String password) {
        set("password", password);
    }

    /**
     * 密码
     */
    public String getPassword() {
        return getStr("password");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    public void setUpdateTime(java.util.Date updateTime) {
        set("updateTime", updateTime);
    }

    public java.util.Date getUpdateTime() {
        return getDate("updateTime");
    }

    /**
     * 是否删除
     */
    public void setIsDelete(Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 是否删除
     */
    public Integer getIsDelete() {
        return getInt("isDelete");
    }

}

