package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends JbootModel<M> implements IBean {

    /**
     * 主键
     */
    public void setId(java.lang.Long id) {
        set("id", id);
    }

    /**
     * 主键
     */
    public java.lang.Long getId() {
        return getLong("id");
    }

    /**
     * 类型 - 0 - 收藏 1 - 点赞 2 - 关注消息 3 - 私发消息 4 - 队伍消息
     */
    public void setType(java.lang.Integer type) {
        set("type", type);
    }

    /**
     * 类型 - 0 - 收藏 1 - 点赞 2 - 关注消息 3 - 私发消息 4 - 队伍消息
     */
    public java.lang.Integer getType() {
        return getInt("type");
    }

    /**
     * 消息发送的用户id
     */
    public void setFromId(java.lang.Long fromId) {
        set("fromId", fromId);
    }

    /**
     * 消息发送的用户id
     */
    public java.lang.Long getFromId() {
        return getLong("fromId");
    }

    /**
     * 消息接收的用户id
     */
    public void setToId(java.lang.Long toId) {
        set("toId", toId);
    }

    /**
     * 消息接收的用户id
     */
    public java.lang.Long getToId() {
        return getLong("toId");
    }

    /**
     * 消息内容
     */
    public void setText(java.lang.String text) {
        set("text", text);
    }

    /**
     * 消息内容
     */
    public java.lang.String getText() {
        return getStr("text");
    }

    /**
     * 头像
     */
    public void setAvatarUrl(java.lang.String avatarUrl) {
        set("avatarUrl", avatarUrl);
    }

    /**
     * 头像
     */
    public java.lang.String getAvatarUrl() {
        return getStr("avatarUrl");
    }

    /**
     * 博客 id
     */
    public void setBlogId(java.lang.Long blogId) {
        set("blogId", blogId);
    }

    /**
     * 博客 id
     */
    public java.lang.Long getBlogId() {
        return getLong("blogId");
    }

    /**
     * 队伍 id
     */
    public void setTeamId(java.lang.Long teamId) {
        set("teamId", teamId);
    }

    /**
     * 队伍 id
     */
    public java.lang.Long getTeamId() {
        return getLong("teamId");
    }

    /**
     * 已读-0 未读 ,1 已读
     */
    public void setIsRead(java.lang.Integer isRead) {
        set("isRead", isRead);
    }

    /**
     * 已读-0 未读 ,1 已读
     */
    public java.lang.Integer getIsRead() {
        return getInt("isRead");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    /**
     * 更新时间
     */
    public void setUpdateTime(java.util.Date updateTime) {
        set("updateTime", updateTime);
    }

    /**
     * 更新时间
     */
    public java.util.Date getUpdateTime() {
        return getDate("updateTime");
    }

    /**
     * 逻辑删除
     */
    public void setIsDelete(java.lang.Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 逻辑删除
     */
    public java.lang.Integer getIsDelete() {
        return getInt("isDelete");
    }

}

