package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTag<M extends BaseTag<M>> extends JbootModel<M> implements IBean {

    /**
     * id
     */
    public void setId(Long id) {
        set("id", id);
    }

    /**
     * id
     */
    public Long getId() {
        return getLong("id");
    }

    /**
     * 标签名称
     */
    public void setTagName(String tagName) {
        set("tagName", tagName);
    }

    /**
     * 标签名称
     */
    public String getTagName() {
        return getStr("tagName");
    }

    /**
     * 用户 id
     */
    public void setUserId(Long userId) {
        set("userId", userId);
    }

    /**
     * 用户 id
     */
    public Long getUserId() {
        return getLong("userId");
    }

    /**
     * 父标签 id
     */
    public void setParentId(Long parentId) {
        set("parentId", parentId);
    }

    /**
     * 父标签 id
     */
    public Long getParentId() {
        return getLong("parentId");
    }

    /**
     * 0 - 不是, 1 - 父标签
     */
    public void setIsParent(Integer isParent) {
        set("isParent", isParent);
    }

    /**
     * 0 - 不是, 1 - 父标签
     */
    public Integer getIsParent() {
        return getInt("isParent");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    public void setUpdateTime(java.util.Date updateTime) {
        set("updateTime", updateTime);
    }

    public java.util.Date getUpdateTime() {
        return getDate("updateTime");
    }

    /**
     * 是否删除
     */
    public void setIsDelete(Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 是否删除
     */
    public Integer getIsDelete() {
        return getInt("isDelete");
    }

}

