package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserTeam<M extends BaseUserTeam<M>> extends JbootModel<M> implements IBean {

    /**
     * id
     */
    public void setId(Long id) {
        set("id", id);
    }

    /**
     * id
     */
    public Long getId() {
        return getLong("id");
    }

    /**
     * 用户id
     */
    public void setUserId(Long userId) {
        set("userId", userId);
    }

    /**
     * 用户id
     */
    public Long getUserId() {
        return getLong("userId");
    }

    /**
     * 队伍id
     */
    public void setTeamId(Long teamId) {
        set("teamId", teamId);
    }

    /**
     * 队伍id
     */
    public Long getTeamId() {
        return getLong("teamId");
    }

    /**
     * 加入时间
     */
    public void setJoinTime(java.util.Date joinTime) {
        set("joinTime", joinTime);
    }

    /**
     * 加入时间
     */
    public java.util.Date getJoinTime() {
        return getDate("joinTime");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    public void setUpdateTime(java.util.Date updateTime) {
        set("updateTime", updateTime);
    }

    public java.util.Date getUpdateTime() {
        return getDate("updateTime");
    }

    /**
     * 是否删除
     */
    public void setIsDelete(Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 是否删除
     */
    public Integer getIsDelete() {
        return getInt("isDelete");
    }

}

