package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends JbootModel<M> implements IBean {

    /**
     * id
     */
    public void setId(java.lang.Long id) {
        set("id", id);
    }

    /**
     * id
     */
    public java.lang.Long getId() {
        return getLong("id");
    }

    /**
     * 标题
     */
    public void setTitle(java.lang.String title) {
        set("title", title);
    }

    /**
     * 标题
     */
    public java.lang.String getTitle() {
        return getStr("title");
    }

    /**
     * 封面图片
     */
    public void setCoverImage(java.lang.String coverImage) {
        set("coverImage", coverImage);
    }

    /**
     * 封面图片
     */
    public java.lang.String getCoverImage() {
        return getStr("coverImage");
    }

    /**
     * 图片列表
     */
    public void setImages(java.lang.String images) {
        set("images", images);
    }

    /**
     * 图片列表
     */
    public java.lang.String getImages() {
        return getStr("images");
    }

    /**
     * 内容
     */
    public void setContent(java.lang.String content) {
        set("content", content);
    }

    /**
     * 内容
     */
    public java.lang.String getContent() {
        return getStr("content");
    }

    /**
     * 作者 id
     */
    public void setUserId(java.lang.Long userId) {
        set("userId", userId);
    }

    /**
     * 作者 id
     */
    public java.lang.Long getUserId() {
        return getLong("userId");
    }

    /**
     * 标签列表
     */
    public void setTags(java.lang.String tags) {
        set("tags", tags);
    }

    /**
     * 标签列表
     */
    public java.lang.String getTags() {
        return getStr("tags");
    }

    /**
     * 浏览数
     */
    public void setViewNum(java.lang.Long viewNum) {
        set("viewNum", viewNum);
    }

    /**
     * 浏览数
     */
    public java.lang.Long getViewNum() {
        return getLong("viewNum");
    }

    /**
     * 点赞数
     */
    public void setLikeNum(java.lang.Long likeNum) {
        set("likeNum", likeNum);
    }

    /**
     * 点赞数
     */
    public java.lang.Long getLikeNum() {
        return getLong("likeNum");
    }

    /**
     * 收藏数
     */
    public void setStarNum(java.lang.Long starNum) {
        set("starNum", starNum);
    }

    /**
     * 收藏数
     */
    public java.lang.Long getStarNum() {
        return getLong("starNum");
    }

    /**
     * 评论数
     */
    public void setCommentNum(java.lang.Long commentNum) {
        set("commentNum", commentNum);
    }

    /**
     * 评论数
     */
    public java.lang.Long getCommentNum() {
        return getLong("commentNum");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    /**
     * 更新时间
     */
    public void setUpdateTime(java.util.Date updateTime) {
        set("updateTime", updateTime);
    }

    /**
     * 更新时间
     */
    public java.util.Date getUpdateTime() {
        return getDate("updateTime");
    }

    /**
     * 是否删除
     */
    public void setIsDelete(java.lang.Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 是否删除
     */
    public java.lang.Integer getIsDelete() {
        return getInt("isDelete");
    }

}

