package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComment<M extends BaseComment<M>> extends JbootModel<M> implements IBean {

    public void setId(java.lang.Long id) {
        set("id", id);
    }

    public java.lang.Long getId() {
        return getLong("id");
    }

    /**
     * 用户id（评论者id）
     */
    public void setUserId(java.lang.Long userId) {
        set("userId", userId);
    }

    /**
     * 用户id（评论者id）
     */
    public java.lang.Long getUserId() {
        return getLong("userId");
    }

    /**
     * 博客id
     */
    public void setBlogId(java.lang.Long blogId) {
        set("blogId", blogId);
    }

    /**
     * 博客id
     */
    public java.lang.Long getBlogId() {
        return getLong("blogId");
    }

    /**
     * 评论内容
     */
    public void setText(java.lang.String text) {
        set("text", text);
    }

    /**
     * 评论内容
     */
    public java.lang.String getText() {
        return getStr("text");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    /**
     * 是否删除
     */
    public void setIsDelete(java.lang.Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 是否删除
     */
    public java.lang.Integer getIsDelete() {
        return getInt("isDelete");
    }

}

