package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFriend<M extends BaseFriend<M>> extends JbootModel<M> implements IBean {

    /**
     * id
     */
    public void setId(java.lang.Long id) {
        set("id", id);
    }

    /**
     * id
     */
    public java.lang.Long getId() {
        return getLong("id");
    }

    /**
     * 用户id（即自己id）
     */
    public void setUserId(java.lang.Long userId) {
        set("userId", userId);
    }

    /**
     * 用户id（即自己id）
     */
    public java.lang.Long getUserId() {
        return getLong("userId");
    }

    /**
     * 好友id
     */
    public void setFriendId(java.lang.Long friendId) {
        set("friendId", friendId);
    }

    /**
     * 好友id
     */
    public java.lang.Long getFriendId() {
        return getLong("friendId");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    /**
     * 更新时间
     */
    public void setUpdateTime(java.util.Date updateTime) {
        set("updateTime", updateTime);
    }

    /**
     * 更新时间
     */
    public java.util.Date getUpdateTime() {
        return getDate("updateTime");
    }

    /**
     * 是否删除
     */
    public void setIsDelete(java.lang.Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 是否删除
     */
    public java.lang.Integer getIsDelete() {
        return getInt("isDelete");
    }

}

