package com.xiaoxu.model.modelbase;

import com.jfinal.plugin.activerecord.IBean;
import io.jboot.db.model.JbootModel;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends JbootModel<M> implements IBean {

    /**
     * id
     */
    public void setId(java.lang.Long id) {
        set("id", id);
    }

    /**
     * id
     */
    public java.lang.Long getId() {
        return getLong("id");
    }

    /**
     * 账号
     */
    public void setUserAccount(java.lang.String userAccount) {
        set("userAccount", userAccount);
    }

    /**
     * 账号
     */
    public java.lang.String getUserAccount() {
        return getStr("userAccount");
    }

    /**
     * 密码
     */
    public void setUserPassword(java.lang.String userPassword) {
        set("userPassword", userPassword);
    }

    /**
     * 密码
     */
    public java.lang.String getUserPassword() {
        return getStr("userPassword");
    }

    /**
     * 用户昵称
     */
    public void setUserName(java.lang.String userName) {
        set("userName", userName);
    }

    /**
     * 用户昵称
     */
    public java.lang.String getUserName() {
        return getStr("userName");
    }

    /**
     * 用户头像
     */
    public void setUserAvatar(java.lang.String userAvatar) {
        set("userAvatar", userAvatar);
    }

    /**
     * 用户头像
     */
    public java.lang.String getUserAvatar() {
        return getStr("userAvatar");
    }

    /**
     * 用户简介
     */
    public void setUserProfile(java.lang.String userProfile) {
        set("userProfile", userProfile);
    }

    /**
     * 用户简介
     */
    public java.lang.String getUserProfile() {
        return getStr("userProfile");
    }

    /**
     * 用户角色：user/admin/ban
     */
    public void setUserRole(java.lang.String userRole) {
        set("userRole", userRole);
    }

    /**
     * 用户角色：user/admin/ban
     */
    public java.lang.String getUserRole() {
        return getStr("userRole");
    }

    /**
     * 用户标签
     */
    public void setTags(java.lang.String tags) {
        set("tags", tags);
    }

    /**
     * 用户标签
     */
    public java.lang.String getTags() {
        return getStr("tags");
    }

    /**
     * 创建时间
     */
    public void setCreateTime(java.util.Date createTime) {
        set("createTime", createTime);
    }

    /**
     * 创建时间
     */
    public java.util.Date getCreateTime() {
        return getDate("createTime");
    }

    /**
     * 更新时间
     */
    public void setUpdateTime(java.util.Date updateTime) {
        set("updateTime", updateTime);
    }

    /**
     * 更新时间
     */
    public java.util.Date getUpdateTime() {
        return getDate("updateTime");
    }

    /**
     * 是否删除
     */
    public void setIsDelete(java.lang.Integer isDelete) {
        set("isDelete", isDelete);
    }

    /**
     * 是否删除
     */
    public java.lang.Integer getIsDelete() {
        return getInt("isDelete");
    }

}

